import type {Config} from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        body: ['Manrope', 'sans-serif'],
        headline: ['Newsreader', 'serif'],
        label: ['Jost', 'sans-serif'],
        serif: ['Instrument Serif', 'serif'],
        code: ['monospace'],
      },
      colors: {
        "on-primary-container": "#605454",
        "background": "#110e0a",
        "tertiary-container": "#e4d7fd",
        "surface": "#110e0a",
        "secondary-dim": "#adbdb1",
        "secondary-container": "#1b2921",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#b3aa9f",
        "on-tertiary": "#5c5271",
        "error-dim": "#c8475d",
        "on-error-container": "#ff97a3",
        "tertiary": "#f1e7ff",
        "error": "#fd6f85",
        "outline": "#7c746b",
        "surface-variant": "#2a251e",
        "on-secondary-fixed-variant": "#59685e",
        "tertiary-fixed-dim": "#d6c9ee",
        "inverse-primary": "#685c5c",
        "on-tertiary-fixed-variant": "#5d5372",
        "surface-container-high": "#241f18",
        "on-primary": "#685c5c",
        "surface-tint": "#fff8f7",
        "surface-container-low": "#16130e",
        "on-tertiary-fixed": "#403755",
        "on-primary-fixed-variant": "#655959",
        "surface-container-highest": "#2a251e",
        "surface-container": "#1d1913",
        "error-container": "#8a1632",
        "tertiary-dim": "#d6c9ee",
        "secondary-fixed-dim": "#d6e7da",
        "on-error": "#490013",
        "primary-container": "#f9e7e7",
        "tertiary-fixed": "#e4d7fd",
        "outline-variant": "#4d473e",
        "inverse-on-surface": "#59544f",
        "primary-dim": "#eddcdc",
        "on-primary-fixed": "#483d3d",
        "secondary": "#bacabe",
        "primary": "#fff8f7",
        "on-secondary": "#35433a",
        "primary-fixed-dim": "#e1d1d1",
        "primary-fixed": "#f0dfde",
        "on-surface": "#efe4d8",
        "on-secondary-container": "#98a89c",
        "surface-dim": "#110e0a",
        "secondary-fixed": "#e5f5e8",
        "inverse-surface": "#fff8f3",
        "on-secondary-fixed": "#3d4b42",
        "on-background": "#efe4d8",
        "on-tertiary-container": "#534968",
        "surface-bright": "#312b23",
        // Midnight Ledger specific (if any unique ones needed)
        "midnight-orange": "#ec5b13",
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        'xs': '0.125rem',
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;
