
// This is an autogenerated file from Firebase Studio.
'use client';

import { ArrowLeft, QrCode } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function ScanPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button asChild variant="ghost" size="icon">
          <Link href="/">
            <ArrowLeft />
          </Link>
        </Button>
        <h1 className="text-2xl font-bold">Scan QR Code</h1>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>QR Code Scanner</CardTitle>
          <CardDescription>
            This feature is coming soon.
          </CardDescription>
        </CardHeader>
        <CardContent className='flex flex-col items-center justify-center text-center text-muted-foreground pt-12'>
            <QrCode className="h-24 w-24 mx-auto mb-4" />
            <p className="font-semibold text-lg">Scan to Add Expense</p>
            <p>Point your camera at a QR code to automatically add a transaction.</p>
        </CardContent>
      </Card>
    </div>
  );
}
