
// This is an autogenerated file from Firebase Studio.
'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Plus, QrCode, Pencil } from 'lucide-react';
import { Button } from './ui/button';

export function FloatingActionButton() {
  const [isOpen, setIsOpen] = useState(false);

  const toggleMenu = () => setIsOpen(!isOpen);

  const menuButtonClasses = "rounded-full bg-secondary text-secondary-foreground w-14 h-14";

  return (
    <div className="fixed bottom-6 left-1/2 -translate-x-1/2 flex items-center justify-center z-50">
       {isOpen && (
        <div
          className="fixed inset-0 bg-black/30 z-40"
          onClick={toggleMenu}
        ></div>
      )}
      <div className="relative z-50 flex items-center justify-center gap-4">
        <div className={`transition-all duration-300 ease-in-out ${isOpen ? 'opacity-100 scale-100' : 'opacity-0 scale-90'}`}>
            <Link href="/add" passHref>
                <Button
                className={menuButtonClasses}
                size="icon"
                aria-label="Add Expense"
                onClick={toggleMenu}
                >
                <Pencil className="h-6 w-6" />
                </Button>
            </Link>
        </div>

        <Button
          className="rounded-full bg-primary w-20 h-20 shadow-lg shadow-primary/30 relative"
          size="icon"
          onClick={toggleMenu}
          aria-expanded={isOpen}
        >
          <Plus className={`h-10 w-10 text-black transition-transform duration-300 ${isOpen ? 'rotate-45' : 'rotate-0'}`} />
        </Button>
        
        <div className={`transition-all duration-300 ease-in-out ${isOpen ? 'opacity-100 scale-100' : 'opacity-0 scale-90'}`}>
            <Link href="/scan" passHref>
                <Button
                className={menuButtonClasses}
                size="icon"
                aria-label="Scan QR Code"
                onClick={toggleMenu}
                >
                <QrCode className="h-6 w-6" />
                </Button>
            </Link>
        </div>
      </div>
    </div>
  );
}
