
// This is an autogenerated file from Firebase Studio.
'use client';
import Link from 'next/link';
import {
  Home,
  Bell,
  Menu,
  Settings,
  CreditCard,
  LogOut,
  Shield,
  Upload,
  FolderKanban,
  Download,
  User,
} from 'lucide-react';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { useLocalStorage } from '@/hooks/use-local-storage';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';
import { Separator } from '@/components/ui/separator';
import { useState } from 'react';
import { useIsMobile } from '@/hooks/use-mobile';
import type { Profile } from '@/lib/types';
import { FloatingActionButton } from './floating-action-button';

export function AppLayout({ children }: { children: React.ReactNode }) {
  const [profile] = useLocalStorage<Profile>('user-profile', {
    avatarUrl: 'https://picsum.photos/100/100',
  });
  const [isSheetOpen, setIsSheetOpen] = useState(false);
  const isMobile = useIsMobile();

  const handleLinkClick = () => {
    setIsSheetOpen(false);
  };

  const menuItems = [
    { href: '/profile', icon: User, label: 'Profile' },
    { href: '/categories', icon: FolderKanban, label: 'Categories' },
    { href: '/import', icon: Upload, label: 'Import' },
    { href: '/export', icon: Download, label: 'Export' },
    { href: '/settings', icon: Settings, label: 'Settings' },
    { href: '#', icon: CreditCard, label: 'Subscription' },
    { href: '#', icon: Shield, label: 'Privacy' },
  ];

  const SheetMenuItems = () => (
    <div className="space-y-8">
       <div className="grid grid-cols-3 gap-4 text-center">
        {menuItems.map(item => (
          <Link href={item.href} key={item.href} onClick={handleLinkClick} className="flex flex-col items-center space-y-2 text-white/80 hover:text-white">
            <div className="p-4 bg-white/10 rounded-2xl">
              <item.icon className="h-8 w-8" />
            </div>
            <span className="text-xs font-semibold">{item.label}</span>
          </Link>
        ))}
      </div>
      <Separator className="bg-white/20" />
      <Button variant="destructive" className="w-full text-lg py-6">
        <LogOut className="mr-2" /> Sign Out
      </Button>
    </div>
  );

  return (
    <div className="flex flex-col h-screen bg-black text-white">
      <header className="flex items-center justify-between p-4">
        <Link href="/profile">
          <Avatar>
            <AvatarImage
              src={profile.avatarUrl}
              alt="User"
              data-ai-hint="person avatar"
            />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </Link>
        <Sheet open={isSheetOpen} onOpenChange={setIsSheetOpen}>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon">
              <Menu className="h-6 w-6" />
            </Button>
          </SheetTrigger>
          <SheetContent
            side={isMobile ? 'bottom' : 'right'}
            className="bg-neutral-900/80 text-white backdrop-blur-xl border-neutral-700 rounded-t-3xl md:rounded-l-3xl md:rounded-t-none"
          >
            <SheetHeader>
              <SheetTitle className="text-primary text-2xl">
                Settings
              </SheetTitle>
            </SheetHeader>
            <div className="flex flex-col space-y-4 py-8">
              <SheetMenuItems />
            </div>
          </SheetContent>
        </Sheet>
      </header>

      <main className="flex-1 overflow-y-auto px-4">{children}</main>

      <footer className="sticky bottom-0 left-0 right-0 bg-black/50 backdrop-blur-lg">
        <div className="flex justify-around items-center p-4 max-w-md mx-auto relative h-20">
          <Link href="/" className="p-2">
            <Home className="h-7 w-7 text-white" />
          </Link>
          
          <Link href="/notifications" className="p-2">
            <Bell className="h-7 w-7 text-white" />
          </Link>
        </div>
      </footer>
      <FloatingActionButton />
    </div>
  );
}
