
// This is an autogenerated file from Firebase Studio.
'use client';
import Link from 'next/link';
import {
  Home,
  Bell,
  Plus,
  Menu,
  Settings,
  CreditCard,
  LogOut,
  Shield,
  Upload,
  FolderKanban,
  Download,
  User,
} from 'lucide-react';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { useLocalStorage } from '@/hooks/use-local-storage';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';
import { Separator } from '@/components/ui/separator';
import { useState } from 'react';
import { useIsMobile } from '@/hooks/use-mobile';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from './ui/tooltip';

export function AppLayout({ children }: { children: React.ReactNode }) {
  const [profile] = useLocalStorage('user-profile', {
    avatarUrl: 'https://picsum.photos/100/100',
  });
  const [isSheetOpen, setIsSheetOpen] = useState(false);
  const isMobile = useIsMobile();

  const handleLinkClick = () => {
    setIsSheetOpen(false);
  };

  const menuItems = [
    { href: '/profile', icon: User, label: 'Profile' },
    { href: '/categories', icon: FolderKanban, label: 'Manage Categories' },
    { href: '/import', icon: Upload, label: 'Import CSV' },
    { href: '/export', icon: Download, label: 'Export Data' },
    { href: '/settings', icon: Settings, label: 'Settings' },
    { href: '#', icon: CreditCard, label: 'Subscription' },
    { href: '#', icon: Shield, label: 'Privacy' },
  ];

  const SheetMenuItems = () => (
    <TooltipProvider>
      <div className="flex items-center justify-around flex-wrap gap-4">
        {menuItems.map(item => (
          <Tooltip key={item.href}>
            <TooltipTrigger asChild>
              <Link href={item.href} onClick={handleLinkClick}>
                <Button
                  variant="outline"
                  size="icon"
                  className="h-16 w-16 rounded-2xl bg-white/10 border-white/20"
                >
                  <item.icon className="h-8 w-8" />
                </Button>
              </Link>
            </TooltipTrigger>
            <TooltipContent>
              <p>{item.label}</p>
            </TooltipContent>
          </Tooltip>
        ))}
      </div>
      <Separator className="my-8 bg-white/20" />
      <Button variant="destructive" className="w-full text-lg py-6">
        <LogOut className="mr-2" /> Sign Out
      </Button>
    </TooltipProvider>
  );

  return (
    <div className="flex flex-col h-screen bg-black text-white">
      <header className="flex items-center justify-between p-4">
        <Link href="/profile">
          <Avatar>
            <AvatarImage
              src={profile.avatarUrl}
              alt="User"
              data-ai-hint="person avatar"
            />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
        </Link>
        <Sheet open={isSheetOpen} onOpenChange={setIsSheetOpen}>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon">
              <Menu className="h-6 w-6" />
            </Button>
          </SheetTrigger>
          <SheetContent
            side={isMobile ? 'bottom' : 'right'}
            className="bg-neutral-800/60 text-white backdrop-blur-xl border-neutral-700 rounded-t-3xl md:rounded-l-3xl md:rounded-t-none"
          >
            <SheetHeader>
              <SheetTitle className="text-primary text-2xl">
                Settings
              </SheetTitle>
            </SheetHeader>
            <div className="flex flex-col space-y-4 py-8">
              <SheetMenuItems />
            </div>
          </SheetContent>
        </Sheet>
      </header>

      <main className="flex-1 overflow-y-auto px-4">{children}</main>

      <footer className="sticky bottom-0 left-0 right-0 bg-black">
        <div className="flex justify-around items-center p-4 max-w-md mx-auto relative">
          <Link href="/" className="p-2">
            <Home className="h-7 w-7 text-white" />
          </Link>
          <Link href="/add" className="absolute -top-6">
            <div className="bg-primary rounded-full p-4 shadow-lg shadow-primary/30">
              <Plus className="h-8 w-8 text-black" />
            </div>
          </Link>
          <Link href="/notifications" className="p-2">
            <Bell className="h-7 w-7 text-white" />
          </Link>
        </div>
      </footer>
    </div>
  );
}
