
// This is an autogenerated file from Firebase Studio.
'use client';
import Link from 'next/link';
import {
  Home,
  Bell,
  Menu,
  Settings,
  CreditCard,
  LogOut,
  Shield,
  Upload,
  FolderKanban,
  Download,
  User,
} from 'lucide-react';
import { Avatar, AvatarImage, AvatarFallback } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { useLocalStorage } from '@/hooks/use-local-storage';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from '@/components/ui/sheet';
import { Separator } from '@/components/ui/separator';
import { useState } from 'react';
import { useIsMobile } from '@/hooks/use-mobile';
import { FloatingActionButton } from './floating-action-button';

type Profile = {
  avatarUrl: string;
};

export function AppLayout({ children }: { children: React.ReactNode }) {
  const [profile] = useLocalStorage<Profile>('user-profile', {
    avatarUrl: 'https://picsum.photos/100/100',
  });
  const [isSheetOpen, setIsSheetOpen] = useState(false);
  const isMobile = useIsMobile();

  const handleLinkClick = () => {
    setIsSheetOpen(false);
  };

  const menuItems = [
    { href: '/profile', icon: User, label: 'Profile' },
    { href: '/categories', icon: FolderKanban, label: 'Categories' },
    { href: '/import', icon: Upload, label: 'Import' },
    { href: '/export', icon: Download, label: 'Export' },
    { href: '/settings', icon: Settings, label: 'Settings' },
    { href: '#', icon: CreditCard, label: 'Subscription' },
    { href: '#', icon: Shield, label: 'Privacy' },
  ];

  const SheetMenuItems = () => (
    <div className="space-y-8">
       <div className="grid grid-cols-3 gap-4 text-center">
        {menuItems.map(item => (
          <Link href={item.href} key={item.href} onClick={handleLinkClick} className="flex flex-col items-center space-y-2 text-white/80 hover:text-white">
            <div className="p-4 bg-white/10 rounded-2xl">
              <item.icon className="h-8 w-8" />
            </div>
            <span className="text-xs font-semibold">{item.label}</span>
          </Link>
        ))}
      </div>
      <Separator className="bg-white/20" />
      <Button variant="destructive" className="w-full text-lg py-6">
        <LogOut className="mr-2" /> Sign Out
      </Button>
    </div>
  );

  return (
    <div className="flex flex-col min-h-screen bg-surface-dim text-on-background relative overflow-x-hidden">
      {/* Midnight Ledger Header */}
      <header className="flex items-center p-6 justify-between sticky top-0 z-50 bg-surface-dim/80 backdrop-blur-md">
        <div className="flex size-10 shrink-0 items-center justify-center rounded-full border border-[#ec5b13]/20 bg-[#ec5b13]/5">
          <span className="material-symbols-outlined text-[#ec5b13]">eco</span>
        </div>
        <h2 className="text-[#ec5b13] font-bold tracking-[0.2em] text-sm uppercase Jost">Bloom</h2>
        <div className="flex w-10 items-center justify-end">
          <button className="relative p-2 rounded-full hover:bg-[#ec5b13]/10 transition-colors">
            <span className="material-symbols-outlined text-on-surface-variant">notifications</span>
            <span className="absolute top-2 right-2 size-2 bg-[#ec5b13] rounded-full border-2 border-surface-dim"></span>
          </button>
        </div>
      </header>

      <main className="flex-1 max-w-7xl mx-auto w-full px-6 py-12 pb-32">
        {children}
      </main>

      {/* BLOOM Bottom Navigation */}
      <nav className="fixed bottom-0 left-0 w-full z-[101] flex justify-around items-center px-4 pb-8 pt-4 bg-surface/90 backdrop-blur-xl border-t border-outline-variant/15">
        <Link href="/" className="flex flex-col items-center justify-center text-outline hover:text-tertiary transition-colors">
          <span className="material-symbols-outlined mb-1">grid_view</span>
          <span className="text-[10px] font-bold tracking-[0.1em] uppercase Jost leading-none">ATRIUM</span>
        </Link>
        <Link href="/categories" className="flex flex-col items-center justify-center text-primary drop-shadow-[0_0_8px_rgba(255,248,247,0.4)] transform scale-110 transition-all duration-500">
          <span className="material-symbols-outlined mb-1">filter_vintage</span>
          <span className="text-[10px] font-bold tracking-[0.1em] uppercase Jost leading-none">GARDENS</span>
        </Link>
        <Link href="/flows" className="flex flex-col items-center justify-center text-outline hover:text-tertiary transition-colors">
          <span className="material-symbols-outlined mb-1">tsunami</span>
          <span className="text-[10px] font-bold tracking-[0.1em] uppercase Jost leading-none">FLOW</span>
        </Link>
        <Link href="/profile" className="flex flex-col items-center justify-center text-outline hover:text-tertiary transition-colors">
          <span className="material-symbols-outlined mb-1">person_2</span>
          <span className="text-[10px] font-bold tracking-[0.1em] uppercase Jost leading-none">PROFILE</span>
        </Link>
      </nav>

      {/* Floating Background Elements for Atmosphere */}
      <div className="fixed top-1/4 -left-32 w-96 h-96 bg-secondary/5 breathing-blob z-0 pointer-events-none"></div>
      <div className="fixed bottom-1/4 -right-32 w-80 h-80 bg-tertiary/5 breathing-blob z-0 pointer-events-none"></div>
    </div>
  );
}
