// This is an autogenerated file from Firebase Studio.
'use client';

import { ArrowLeft, Upload } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';

export default function ImportPage() {
  const { toast } = useToast();

  const handleImport = () => {
    // This is a placeholder for the actual CSV import logic.
    toast({
      title: 'Import in Progress',
      description: 'We are processing your CSV file. This may take a moment.',
    });
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button asChild variant="ghost" size="icon">
          <Link href="/">
            <ArrowLeft />
          </Link>
        </Button>
        <h1 className="text-2xl font-bold">Import Transactions</h1>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Upload CSV File</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <p className="text-muted-foreground">
            Upload a CSV file with your transactions. The file should have the
            following columns: Date, Merchant, Amount, Category, Subcategory,
            Notes.
          </p>
          <Input type="file" accept=".csv" />
          <Button onClick={handleImport} className="w-full" size="lg">
            <Upload className="mr-2 h-4 w-4" /> Import File
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
