// This is an autogenerated file from Firebase Studio.
'use client';

import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

export default function NotificationsPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button asChild variant="ghost" size="icon">
          <Link href="/">
            <ArrowLeft />
          </Link>
        </Button>
        <h1 className="text-2xl font-bold">Notifications</h1>
      </div>
      <div className="text-center text-muted-foreground pt-12">
        <p>Notification settings will be available here.</p>
        <p>Stay tuned!</p>
      </div>
    </div>
  );
}
